<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
  <xacro:property name="camera_length" value="0.01"/>
  <xacro:property name="camera_width" value="0.1"/>
  <xacro:property name="camera_height" value="0.05"/>
  <link name="camera_link" >
    <visual>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}"
                       xyz="0 0 0" rpy="0 0 0" />
  </link>                     
  <joint name="base_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${(camera_length + base_length) /2} 0 0" rpy="0 1.57 0"/>
  </joint>

  <gazebo reference="camera_link">
  <sensor name="camera_sensor" type="camera">
    <pose>0 0 0 0 0 0</pose>
    <visualize>true</visualize>
    <update_rate>10.0</update_rate>

    <camera>
      <horizontal_fov>1.047</horizontal_fov>
      <image>
        <width>640</width>
        <height>480</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.01</near>
        <far>10.0</far>
      </clip>
    </camera>

    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <camera_name>camera</camera_name>
      <image_topic_name>image_raw</image_topic_name>
      <frame_name>camera_link</frame_name>
    </plugin>
  </sensor>
</gazebo>

</robot>