<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="cyl_link" params="name length radius mass color">
  <link name="${name}">
    <inertial>
      <origin xyz="0 0 ${length/2}"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${(mass*(3*radius*radius + length*length))/12}"
        iyy="${(mass*(3*radius*radius + length*length))/12}"
        izz="${(mass*radius*radius)/2}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${length/2}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="${color}"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${length/2}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>
  </link>
</xacro:macro>

</robot>
